CREATE OR REPLACE DATABASE STREAMLIT_DB;
CREATE OR REPLACE SCHEMA STREAMLIT_SCHEMA;

CREATE OR REPLACE TABLE CALL_TRANSCRIPTS (
  CALL_ID STRING,
  AGENT_NAME STRING,
  CUSTOMER_NAME STRING,
  CALL_DATE DATE,
  TRANSCRIPT TEXT
);

SELECT * FROM CALL_TRANSCRIPTS LIMIT 30;
